### ISSUE TITLE
Unable to load certificate and/or private key error

### ISSUE THREAD

**Issue by BillBardon** [Ylianst/Authenticode-JS#2] opened 2022-06-16 21:04 UTC
Went round and round with Sectigo, finally got a certificate. Had to convert to pem format. When signing with authenticode-js, the title error was displayed. Looking in the code, I found that with one change I could make it work.

At line 67, the program is looking for the private key:

var PemKeys = pem.split('-----BEGIN RSA PRIVATE KEY-----');

but in my pem file, the header is "-----BEGIN PRIVATE KEY-----". I don't know if it was a mistake in how I converted the file or something else. I edited my pem file and added the "RSA " where indicated, and reran the code signing. This time it worked. info showed proper signing, and Properties in Windows displayed my certificate.

**Comment by Ylianst** [comment] 2022-06-18 16:23
Thanks for reporting this! I just put in a fix for it. Will be in v1.0.4. I will publish it in a minute.

**Comment by Ylianst** [comment] 2022-06-18 16:29
[v1.0.4 is out on NPM.](https://www.npmjs.com/package/authenticode-js)

**Comment by LPJon** [comment] 2022-06-20 05:21
This is directly related to issue filed in MeshCentral [here.](https://github.com/Ylianst/MeshCentral/issues/4119) It appears to be the same issue.

**Comment by Ylianst** [comment] 2022-06-20 21:36
Ok, I fixed this one in v1.0.4, I will close it since it's been confirmed fixed in the MeshCentral repo by @LPJon, but do re-open if needed.

**Closed as completed by Ylianst** 2022-06-20 21:36 UTC
Labels: bug, Fixed - Please Verify & Close
